# Generated by Django 5.0 on 2023-12-21 00:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id_insti', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(80)], verbose_name='Nombre Institucion')),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(80)], verbose_name='Nombre Inscrito')),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(9)])),
                ('fecha_inscri', models.DateField(auto_now_add=True, verbose_name='Fecha Inscripcion')),
                ('hora_inscri', models.TimeField(auto_now_add=True, verbose_name='Hora Inscripcion')),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO ASISTEN', 'No Asisten')], max_length=15)),
                ('observacion', models.CharField(max_length=250)),
                ('id_institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='evfinal_App.instituciones')),
            ],
        ),
    ]
